/**
 * FamilyPD Progress Review PDF generator
 * Build 8.1
 */
const FPDReviewDocumentServiceV80 = (function () {
  'use strict';

  const PILLARS = [
    { key: 'health', label: 'Health' },
    { key: 'relationships', label: 'Relationships' },
    { key: 'education', label: 'Education' },
    { key: 'finances', label: 'Finances' },
    { key: 'goals', label: 'Goals' }
  ];

  function createReviewFiles(reviewId) {
    const review = FPDReviewServiceV80.getReviewById(reviewId);
    const destination = FPDReviewServiceV80.getWorkspaceFolder('generated', true);
    if (!destination) {
      throw new Error(FPDDriveFileServiceV10.connectionMessage());
    }

    const safeLabel = sanitizeFileName_(review.periodLabel || review.reviewDate || 'Progress Review');
    const baseName = 'FamilyPD Progress Review - ' + safeLabel;
    const document = DocumentApp.create(baseName);
    const body = document.getBody();
    body.clear();

    addTitle_(body, 'Family Progress Review');
    body.appendParagraph(review.periodLabel)
      .setHeading(DocumentApp.ParagraphHeading.HEADING2)
      .setAlignment(DocumentApp.HorizontalAlignment.CENTER);
    body.appendParagraph('Review date: ' + friendlyDate_(review.reviewDate))
      .setAlignment(DocumentApp.HorizontalAlignment.CENTER);
    body.appendHorizontalRule();

    addHeading_(body, 'Five-Pillar Check-In');
    const table = body.appendTable();
    const header = table.appendTableRow();
    header.appendTableCell('Pillar');
    header.appendTableCell('Rating');
    header.appendTableCell('Reflection');

    PILLARS.forEach(function (pillar) {
      const row = table.appendTableRow();
      const rating = Number(review.ratings && review.ratings[pillar.key] || 1);
      row.appendTableCell(pillar.label);
      row.appendTableCell(rating + ' of 5');
      row.appendTableCell(ratingText_(rating));
    });

    addSection_(body, 'Wins and Progress', review.wins);
    addSection_(body, 'Needs Attention', review.needsAttention);
    addSection_(body, 'Decisions Made', review.decisions);
    addSection_(body, 'Next Steps', review.nextSteps);

    if (review.nextMeetingDate) {
      addSection_(body, 'Next Planned Meeting', friendlyDate_(review.nextMeetingDate));
    }
    addSection_(body, 'Additional Notes', review.notes);

    body.appendHorizontalRule();
    body.appendParagraph(
      'FamilyPD reminder: Focus on practical next steps. Do not include passwords, account numbers, identification numbers, exact dates of birth, medical record details, or other sensitive information.'
    ).setItalic(true);

    document.saveAndClose();

    const documentId = document.getId();
    const movedDocument = FPDDriveFileServiceV10.moveFile(documentId, destination.id);
    const pdfBlob = FPDDriveFileServiceV10.exportPdf(documentId, baseName + '.pdf');
    const pdfFile = FPDDriveFileServiceV10.createBlobFile(
      destination.id,
      baseName + '.pdf',
      pdfBlob,
      'Generated by the FamilyPD Progress Review Center.'
    );

    return {
      ok: true,
      documentId: documentId,
      documentUrl: movedDocument.webViewLink || 'https://docs.google.com/document/d/' + documentId + '/edit',
      pdfId: pdfFile.id,
      pdfUrl: pdfFile.webViewLink || 'https://drive.google.com/open?id=' + encodeURIComponent(pdfFile.id),
      folderUrl: destination.webViewLink || FPDDriveFileServiceV10.folderUrl(destination.id),
      fileName: pdfFile.name || (baseName + '.pdf')
    };
  }

  function addTitle_(body, text) {
    body.appendParagraph(text)
      .setHeading(DocumentApp.ParagraphHeading.TITLE)
      .setAlignment(DocumentApp.HorizontalAlignment.CENTER);
  }

  function addHeading_(body, text) {
    body.appendParagraph(text).setHeading(DocumentApp.ParagraphHeading.HEADING1);
  }

  function addSection_(body, heading, value) {
    addHeading_(body, heading);
    body.appendParagraph(clean_(value) || 'No notes were entered for this section.');
  }

  function ratingText_(rating) {
    const labels = {
      1: 'Immediate focus needed',
      2: 'Needs improvement',
      3: 'Stable / developing',
      4: 'Strong progress',
      5: 'Doing very well'
    };
    return labels[rating] || labels[1];
  }

  function friendlyDate_(value) {
    const text = clean_(value);
    if (!/^\d{4}-\d{2}-\d{2}$/.test(text)) return text;
    const parts = text.split('-');
    return parts[1] + '/' + parts[2] + '/' + parts[0];
  }

  function sanitizeFileName_(value) {
    return clean_(value)
      .replace(/[\\/:*?"<>|#%{}~&]/g, '-')
      .replace(/\s+/g, ' ')
      .slice(0, 100) || 'Progress Review';
  }

  function clean_(value) {
    return value === null || value === undefined ? '' : String(value).trim();
  }

  return {
    createReviewFiles: createReviewFiles
  };
}());

function fpdCreateProgressReviewPdf(reviewId) {
  return FPDReviewDocumentServiceV80.createReviewFiles(reviewId);
}
